### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe with ST Build 3103

### ISSUE THREAD

**Issue by kachar** [phpfmt/fmt#130]
Description:
When doing format now on Windows machine phpfmt does not update the code and wild console error appears.

Anyway this does not happen if there are syntax errors in the php file. Then the status bar indicates that with `phpfmt: format failed - syntax errors found`

Failing code:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\user1144\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 755, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\user1144\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 242, in dofmt
    res, err = p.communicate()
  File "./subprocess.py", line 928, in communicate
  File "./subprocess.py", line 1206, in _communicate
BrokenPipeError: [Errno 32] Broken pipe
```

Expected result:
```
Code to be formatted according the configuration
```

Actual result:
```
Error in console appears
```

Your configuration:
```
{
	"format_on_save": true,
	"indent_with_space": 4,
	"passes":
	[
		"YodaComparisons"
	],
	"php_bin": "C:\\php\\php.exe",
	"psr2": true,
	"version": 1
}


PHP 5.6.18 (cli) (built: Feb  3 2016 17:19:47)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by ccirello** [comment]
Have you tried restarting Sublime Text?

**Comment by kachar** [comment]
Many many times :)
I have this problem for over 2 weeks now

**Comment by ccirello** [comment]
I just tried to reproduce here on my own local Windows box, and it works just fine. Must be something specific to your computer.

**Comment by ccirello** [comment]
https://github.com/phpfmt/fmt/issues/108 this might be relevant for you.
