### ISSUE TITLE
No longer fixing - getting error TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by manticorp** [phpfmt/fmt#143]
## Description:

When trying to format a file, I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\ME\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 819, in run
    dogeneratephpdoc(self, self.view)
  File "C:\Users\ME\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 285, in dogeneratephpdoc
    dirnm, sfn = os.path.split(uri)
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

And the file doesn't format

## Failing code:

Any PHP code

## Expected result:

Formatted code

## Actual result:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\ME\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 819, in run
    dogeneratephpdoc(self, self.view)
  File "C:\Users\ME\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 285, in dogeneratephpdoc
    dirnm, sfn = os.path.split(uri)
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

## Your configuration:
```
{
	"enable_auto_align": true,
	"format_on_save": false,
	"passes":
	[
		"AddMissingParentheses",
		"AlignConstVisibilityEquals",
		"AlignDoubleArrow",
		"AlignDoubleSlashComments",
		"AlignEquals",
		"AlignGroupDoubleArrow",
		"ConvertOpenTagWithEcho",
		"GeneratePHPDoc",
		"LongArray",
		"PrettyPrintDocBlocks",
		"ReindentAndAlignObjOps",
		"ReindentSwitchBlocks",
		"RemoveIncludeParentheses",
		"RemoveSemicolonAfterCurly",
		"SpaceBetweenMethods"
	],
	"php_bin": "C:\\path\\to\\php7\\php7.exe",
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"smart_linebreak_after_curly": true,
	"version": 4
}

```

**Comment by ccirello** [comment]
Hi, unfortunately we don't have a windows maintainer anymore. Can you provide a fix?

**Comment by ccirello** [comment]
Please open a PR if you can provide a fix for this.
